/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Feature Flags
 */
export const ENABLE_DEBUG_PANEL = false;

/**
 * Translations of displayed text
 */
export const TRANSLATIONS = {
  en: {
    title: "Yakiniku Master",
    ultimate: "ULTIMATE",
    easy: "Easy",
    normal: "Normal",
    hard: "Hard",
    hp: "Health",
    scoring: "Scoring",
    scoringDesc: "Score = 10 x SideA x SideB",
    well: "Well (x2)",
    half: "Half/Over (x1)",
    other: "Other (x0)",
    hpLabel: "Health:",
    hpDesc: "Raw/Burnt -5 | Over -1 | Double Well +1",
    controls: "Controls:",
    controlsDesc: "Drag to grill ➔ Click to flip ➔ Drag to sauce.",
    startGame: "START GAME",
    gameOver: "GAME OVER",
    mainMenu: "MAIN MENU",
    god: "Yakiniku God!",
    chef: "Master Chef!",
    practice: "Keep Practicing!",
    debug: "Debug: Cooking",
    pause: "Pause",
    resume: "Resume",
    recentScores: "Recent Scores",
    sideA: "Side A",
    sideB: "Side B",
    none: "None",
    godlike: "GODLIKE!",
    delicious: "DELICIOUS",
    ok: "OK",
    bad: "BAD",
    failed: "FAILED...",
    timeLeft: "Time Left",
    sauce: "Sauce",
    timeBonus: "TIME BONUS!",
    language: "Language",
    score: "Score",
    time: "Time",
    rawLabel: "Raw",
    leaderboard: "Leaderboard",
    submit: "Submit",
    namePlaceholder: "Enter Name",
    rank: "Rank",
    player: "Player",
    loading: "Loading...",
    submitting: "Submitting...",
    success: "Score Saved!",
    noScoresYet: "No scores yet for",
    easyLeaderboard: "Easy Leaderboard",
    normalLeaderboard: "Normal Leaderboard",
    hardLeaderboard: "Hard Leaderboard"
  },
  zh: {
    title: "燒肉大師",
    ultimate: "終極版",
    easy: "簡單",
    normal: "普通",
    hard: "困難",
    hp: "健康值",
    scoring: "計分方式",
    scoringDesc: "總分 = 10 x A面係數 x B面係數",
    well: "完美熟度 (係數 2)",
    half: "半熟/過熟 (係數 1)",
    other: "其他 (係數 0)",
    hpLabel: "健康值：",
    hpDesc: "生/焦 -5 | 過熟 -1 | 雙面完美 +1",
    controls: "操作方式：",
    controlsDesc: "拖曳至烤網 ➔ 點擊翻面 ➔ 拖曳至醬汁",
    startGame: "開始遊戲",
    gameOver: "遊戲結束",
    mainMenu: "返回主選單",
    god: "燒肉之神！",
    chef: "大廚！",
    practice: "再接再厲！",
    debug: "除錯：烹飪中",
    pause: "暫停",
    resume: "繼續",
    recentScores: "近期得分",
    sideA: "A 面",
    sideB: "B 面",
    none: "無",
    godlike: "神乎其技！",
    delicious: "極致美味",
    ok: "還可以",
    bad: "太差了",
    failed: "失敗...",
    timeLeft: "剩餘時間",
    sauce: "醬汁",
    timeBonus: "時間獎勵！",
    language: "語言選擇",
    score: "得分",
    time: "時間",
    rawLabel: "生肉",
    leaderboard: "全球排行榜",
    submit: "提交分數",
    namePlaceholder: "輸入大名",
    rank: "排名",
    player: "玩家",
    loading: "載入中...",
    submitting: "提交中...",
    success: "分數已儲存！",
    noScoresYet: "目前尚無排名：",
    easyLeaderboard: "簡單模式排行榜",
    normalLeaderboard: "普通模式排行榜",
    hardLeaderboard: "困難模式排行榜"
  }
};
